site_name: DutyController
repo_url: https://github.com/mattgialelis/dutycontroller
repo_name: dutycontroller
edit_uri: edit/master/docs/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tracking
  icon:
    edit: material/pencil
    view: material/eye
nav:
  - Overview: index.md
  - Resources:
      - Getting Started with PagerDuty: resources/pagerduty-Intro.md
      - PagerDuty Integration:
          - Business Service: resources/pagerduty/businessService.md
          - Services: resources/pagerduty/services.md
          - Orchestration Routes: resources/pagerduty/orchestrationRoutes.md
  - Installation:
      - Helm: installation/helm.md
      - Helm Chart Values: installation/helmvalues.md
  - How To Update These Docs: how_to_update.md
plugins:
  - awesome-pages
  - search
  - mike
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
