# permissions for end users to view businessservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dutycontroller
    app.kubernetes.io/managed-by: kustomize
  name: businessservice-viewer-role
rules:
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - businessservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - businessservices/status
  verbs:
  - get
