---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - businessservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - businessservices/finalizers
  verbs:
  - update
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - businessservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - pagerduty.dutycontroller.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
