{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dutycontroller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dutycontroller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "dutycontroller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
