apiVersion: v1
kind: Service
metadata:
  name: {{ include "dutycontroller.fullname" . }}
  labels:
    {{- include "dutycontroller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      protocol: {{ default "TCP" .Values.service.ports.protocol }}
    {{- if .Values.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "dutycontroller.selectorLabels" . | nindent 4 }}
