apiVersion: pagerduty.dutycontroller.io/v1beta1
kind: Orchestrationroutes
metadata:
  labels:
    app.kubernetes.io/name: dutycontroller
    app.kubernetes.io/managed-by: kustomize
  name: orchestrationroutes-sample
spec:
  # TODO(user): Add fields here
