name: Publish docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_docs_page:
   runs-on: ubuntu-20.04
   steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install mkdocs-material \
          mkdocs-git-revision-date-localized-plugin \
          mkdocs-awesome-pages-plugin \
          mike

      - run: |
          git fetch
          mike deploy --ignore --push  latest
          mike set-default --push latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
