name: Publish docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_docs_page:
   runs-on: ubuntu-20.04
   steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material \
          mkdocs-git-revision-date-localized-plugin \
          mkdocs-awesome-pages-plugin \
          mike

      - run: mike deploy --ignore --push --ignore-remote-status latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
