name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/charts/**'
    workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Go
        uses: actions/setup-go@v5
        id: setup-go
        with:
          go-version-file: "go.mod"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Make CRDS
        run: |
          make helm-crds

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          chart_dir: deploy/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

