name: release-please

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deploy/charts/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.PAT }}
